
=== Test project_root: /tmp/pytest-of-runner/pytest-0/project62


Invoking dbt with ['run', '--select', 'my_upstream_model']
[0m16:13:30  Running with dbt=1.10.5
[0m16:13:30  Registered adapter: firebolt=1.9.4
[0m16:13:30  Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m16:13:30  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 8 unused configuration paths:
- models.base
- seeds.test
- seeds.base
- snapshots.test
- snapshots.base
- data_tests.test
- data_tests.base
- unit_tests.base
[0m16:13:31  Found 2 models, 464 macros, 1 unit test
[0m16:13:31  
[0m16:13:31  Concurrency: 1 threads (target='default')
[0m16:13:31  
[0m16:13:31  1 of 1 START sql view model my_upstream_model .................................. [RUN]
[0m16:13:31  1 of 1 OK created sql view model my_upstream_model ............................. [[32mSUCCESS[0m in 0.09s]
[0m16:13:31  
[0m16:13:31  Finished running 1 view model in 0 hours 0 minutes and 0.22 seconds (0.22s).
[0m16:13:31  
[0m16:13:31  [32mCompleted successfully[0m
[0m16:13:31  
[0m16:13:31  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=1


Invoking dbt with ['test', '--select', 'my_model']
[0m16:13:31  Running with dbt=1.10.5
[0m16:13:31  Registered adapter: firebolt=1.9.4
[0m16:13:31  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 8 unused configuration paths:
- models.base
- seeds.test
- seeds.base
- snapshots.test
- snapshots.base
- data_tests.test
- data_tests.base
- unit_tests.base
[0m16:13:31  Found 2 models, 464 macros, 1 unit test
[0m16:13:31  
[0m16:13:31  Concurrency: 1 threads (target='default')
[0m16:13:31  
[0m16:13:31  1 of 1 START unit_test my_model::test_my_model ................................. [RUN]
[0m16:13:31  1 of 1 ERROR my_model::test_my_model ........................................... [[31mERROR[0m in 0.11s]
[0m16:13:31  
[0m16:13:31  Finished running 1 unit test in 0 hours 0 minutes and 0.18 seconds (0.18s).
[0m16:13:31  
[0m16:13:31  [31mCompleted with 1 error, 0 partial successes, and 0 warnings:[0m
[0m16:13:31  
[0m16:13:31  [31mFailure in unit_test test_my_model (models/schema.yml)[0m
[0m16:13:31    Runtime Error in unit_test test_my_model (models/schema.yml)
  An error occurred during execution of unit test 'test_my_model'. There may be an error in the unit test definition: check the data types.
   Runtime Error
    Error executing query:
    {
      "errors": [
        {
          "description": "CREATE DIMENSION TABLE AS SELECT is not supported in Firebolt Core"
        }
      ],
      "query": {
        "query_id": "9bc4c878-bb31-4c01-bea9-386210f2b3ca",
        "query_label": null,
        "request_id": "011b8455-13bb-4fe2-b76f-f475cce8d89b"
      },
      "statistics": {
        "elapsed": 0.0
      }
    }
    
[0m16:13:31  
[0m16:13:31  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=1
