
=== Test project_root: /tmp/pytest-of-runner/pytest-0/project26


Invoking dbt with ['seed']
[0m18:11:59  Running with dbt=1.7.7
[0m18:11:59  Registered adapter: firebolt=1.5.0
[0m18:11:59  Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m18:12:00  Found 8 models, 1 seed, 0 sources, 0 exposures, 0 metrics, 418 macros, 0 groups, 0 semantic models
[0m18:12:00  
[0m18:12:02  Concurrency: 1 threads (target='default')
[0m18:12:02  
[0m18:12:02  1 of 1 START seed file seed .................................................... [RUN]
[0m18:12:03  1 of 1 OK loaded seed file public.seed ......................................... [[32mINSERT 100[0m in 1.76s]
[0m18:12:03  
[0m18:12:03  Finished running 1 seed in 0 hours 0 minutes and 3.23 seconds (3.23s).
[0m18:12:03  
[0m18:12:03  [32mCompleted successfully[0m
[0m18:12:03  
[0m18:12:03  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1


Invoking dbt with ['run']
[0m18:12:03  Running with dbt=1.7.7
[0m18:12:03  Registered adapter: firebolt=1.5.0
[0m18:12:03  Found 8 models, 1 seed, 0 sources, 0 exposures, 0 metrics, 418 macros, 0 groups, 0 semantic models
[0m18:12:03  
[0m18:12:05  Concurrency: 1 threads (target='default')
[0m18:12:05  
[0m18:12:05  1 of 7 START sql incremental model advanced_incremental ........................ [RUN]
[0m18:12:07  1 of 7 OK created sql incremental model advanced_incremental ................... [[32mSUCCESS[0m in 1.67s]
[0m18:12:07  2 of 7 START sql table model compound_sort ..................................... [RUN]
[0m18:12:08  2 of 7 OK created sql table model compound_sort ................................ [[32mSUCCESS[0m in 1.63s]
[0m18:12:08  3 of 7 START sql incremental model incremental ................................. [RUN]
[0m18:12:10  3 of 7 OK created sql incremental model incremental ............................ [[32mSUCCESS[0m in 1.74s]
[0m18:12:10  4 of 7 START sql table model interleaved_sort .................................. [RUN]
[0m18:12:11  4 of 7 ERROR creating sql table model interleaved_sort ......................... [[31mERROR[0m in 0.52s]
[0m18:12:11  5 of 7 START sql table model materialized ...................................... [RUN]
[0m18:12:11  5 of 7 ERROR creating sql table model materialized ............................. [[31mERROR[0m in 0.32s]
[0m18:12:11  6 of 7 START sql view model view_model ......................................... [RUN]
[0m18:12:11  6 of 7 ERROR creating sql view model view_model ................................ [[31mERROR[0m in 0.30s]
[0m18:12:11  7 of 7 SKIP relation public.get_and_ref ........................................ [[33mSKIP[0m]
[0m18:12:11  
[0m18:12:11  Finished running 2 incremental models, 3 table models, 2 view models in 0 hours 0 minutes and 7.64 seconds (7.64s).
[0m18:12:11  
[0m18:12:11  [31mCompleted with 3 errors and 0 warnings:[0m
[0m18:12:11  
[0m18:12:11    Runtime Error in model interleaved_sort (models/interleaved_sort.sql)
  Runtime Error
    Database Error
      Error executing query:
      Received error from remote server /core/v1/engineRevisions:getByIds. HTTP status code: 503 Service Unavailable, body: {"error":"connection error: desc = \"transport: Error while dialing: dial tcp :3001: connect: connection refused\"","code":14,"message":"connection error: desc = \"transport: Error while dialing: dial tcp :3001: connect: connection refused\"","details":[]}
      
[0m18:12:11  
[0m18:12:11    Runtime Error in model materialized (models/materialized.sql)
  Runtime Error
    Database Error
      Error executing query:
      Received error from remote server /core/v1/accounts/01h9g6nnqsrtc617763xer77ah/bindings?page.first=10000. HTTP status code: 503 Service Unavailable, body: {"error":"connection error: desc = \"transport: Error while dialing: dial tcp :3001: connect: connection refused\"","code":14,"message":"connection error: desc = \"transport: Error while dialing: dial tcp :3001: connect: connection refused\"","details":[]}
      
[0m18:12:11  
[0m18:12:11    Runtime Error in model view_model (models/view_model.sql)
  Runtime Error
    Database Error
      Error executing query:
      Received error from remote server /core/v1/accounts/01h9g6nnqsrtc617763xer77ah/bindings?page.first=10000. HTTP status code: 503 Service Unavailable, body: {"error":"connection error: desc = \"transport: Error while dialing: dial tcp :3001: connect: connection refused\"","code":14,"message":"connection error: desc = \"transport: Error while dialing: dial tcp :3001: connect: connection refused\"","details":[]}
      
[0m18:12:11  
[0m18:12:11  Done. PASS=3 WARN=0 ERROR=3 SKIP=1 TOTAL=7
