
=== Test project_root: /tmp/pytest-of-runner/pytest-0/project16


Invoking dbt with ['run', '-s', '+my_model']
[0m16:44:57  Running with dbt=1.7.6
[0m16:44:57  Registered adapter: firebolt=1.5.0
[0m16:44:57  Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m16:44:58  [[33mWARNING[0m]: Did not find matching node for patch with name 'my_model_error' in the 'models' section of file 'models/constraints_schema.yml'
[0m16:44:58  [[33mWARNING[0m]: Did not find matching node for patch with name 'my_model_wrong_order' in the 'models' section of file 'models/constraints_schema.yml'
[0m16:44:58  [[33mWARNING[0m]: Did not find matching node for patch with name 'my_model_wrong_name' in the 'models' section of file 'models/constraints_schema.yml'
[0m16:44:58  [[33mWARNING[0m]: Test 'test.test.unique_my_model_error_id.8d2ff7a7b1' (models/constraints_schema.yml) depends on a node named 'my_model_error' in package '' which was not found
[0m16:44:58  [[33mWARNING[0m]: Test 'test.test.unique_my_model_wrong_order_id.605135652f' (models/constraints_schema.yml) depends on a node named 'my_model_wrong_order' in package '' which was not found
[0m16:44:58  [[33mWARNING[0m]: Test 'test.test.unique_my_model_wrong_name_id.ca0635fa7d' (models/constraints_schema.yml) depends on a node named 'my_model_wrong_name' in package '' which was not found
[0m16:44:58  Found 2 models, 1 test, 0 sources, 0 exposures, 0 metrics, 418 macros, 0 groups, 0 semantic models
[0m16:44:58  
[0m16:45:00  Concurrency: 1 threads (target='default')
[0m16:45:00  
[0m16:45:00  1 of 2 START sql table model foreign_key_model ................................. [RUN]
[0m16:45:01  [[33mWARNING[0m]: The constraint type unique is not enforced by firebolt. The
constraint will be included in this model's DDL statement, but it will not
guarantee anything about the underlying data. Set 'warn_unenforced: false' on
this constraint to ignore this warning.
[0m16:45:01  [[33mWARNING[0m]: The constraint type primary_key is not supported by
firebolt, and will be ignored. Set 'warn_unsupported: false' on this constraint
to ignore this warning.
[0m16:45:01  1 of 2 ERROR creating sql table model foreign_key_model ........................ [[31mERROR[0m in 1.39s]
[0m16:45:01  2 of 2 SKIP relation public.my_model ........................................... [[33mSKIP[0m]
[0m16:45:01  
[0m16:45:01  Finished running 2 table models in 0 hours 0 minutes and 3.72 seconds (3.72s).
[0m16:45:01  
[0m16:45:01  [31mCompleted with 1 error and 0 warnings:[0m
[0m16:45:01  
[0m16:45:01    Runtime Error in model foreign_key_model (models/foreign_key_model.sql)
  Error executing query:
  Invalid create table. Unique constraint is not supported. Remove it from the statement and retry
  
[0m16:45:01  
[0m16:45:01  Done. PASS=0 WARN=0 ERROR=1 SKIP=1 TOTAL=2
