{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"AssertionError: dbt exit state did not match expected","children":[{"name":"test_simple_copy","uid":"63e021223c7c4c46","parentUid":"716bf23f50e1373ebbe2cc6c2f01a3ef","status":"failed","time":{"start":1753720656103,"stop":1753720656619,"duration":516},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_case_insensitivity","uid":"830570347ba52786","parentUid":"716bf23f50e1373ebbe2cc6c2f01a3ef","status":"failed","time":{"start":1753720719345,"stop":1753720720343,"duration":998},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"716bf23f50e1373ebbe2cc6c2f01a3ef"},{"name":"AssertionError: assert \"Invalid column name: 'invalid_column_name' in unit test fixture for expected output.\" in '\\x1b[0m16:38:41  Running with dbt=1.10.5\\n\\x1b[0m16:38:41  Registered adapter: firebolt=1.9.4\\n\\x1b[0m16:38:41  [\\x1b[33mWARNING\\x1b[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.\\nThere are 8 unused configuration paths:\\n- models.base\\n- seeds.base\\n- seeds.test\\n- snapshots.base\\n- snapshots.test\\n- data_tests.base\\n- data_tests.test\\n- unit_tests.base\\n\\x1b[0m16:38:41  Found 2 models, 464 macros, 2 unit tests\\n\\x1b[0m16:38:41  \\n\\x1b[0m16:38:41  Concurrency: 1 threads (target=\\'default\\')\\n\\x1b[0m16:38:41  \\n\\x1b[0m16:38:41  1 of 1 START unit_test my_model::test_invalid_expect_column_name ............... [RUN]\\n\\x1b[0m16:38:42  1 of 1 ERROR my_model::test_invalid_expect_column_name ......................... [\\x1b[31mERROR\\x1b[0m in 0.11s]\\n\\x1b[0m16:38:42  \\n\\x1b[0m16:38:42  Finished running 1 unit test in 0 hours 0 minutes and 0.18 seconds (0.18s).\\n\\x1b[0m16:38:42  \\n\\x1b[0m16:38:42  \\x1b[31mCompleted with 1 error, 0 partial successes, and 0 warnings:\\x1b[0m\\n\\x1b[0m16:38:42  \\n\\x1b[0m16:38:42  \\x1b[31mFailure in unit_test test_invalid_expect_column_name (models/unit_tests.yml)\\x1b[0m\\n\\x1b[0m16:38:42    Runtime Error in unit_test test_invalid_expect_column_name (models/unit_tests.yml)\\n  An error occurred during execution of unit test \\'test_invalid_expect_column_name\\'. There may be an error in the unit test definition: check the data types.\\n   Runtime Error\\n    Error executing query:\\n    {\\n      \"errors\": [\\n        {\\n          \"description\": \"CREATE DIMENSION TABLE AS SELECT is not supported in Firebolt Core\"\\n        }\\n      ],\\n      \"query\": {\\n        \"query_id\": \"1a00b4a8-3ff9-49e8-9be0-df723a747945\",\\n        \"query_label\": null,\\n        \"request_id\": \"214e7d4f-72a5-4132-a171-7a633438b1c0\"\\n      },\\n      \"statistics\": {\\n        \"elapsed\": 0.0\\n      }\\n    }\\n    \\n\\x1b[0m16:38:42  \\n\\x1b[0m16:38:42  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 NO-OP=0 TOTAL=1\\n'","children":[{"name":"test_invalid_input","uid":"bac5dee1a30fa632","parentUid":"0984621ee1237aa41f0695171dc0528b","status":"failed","time":{"start":1753720720824,"stop":1753720722120,"duration":1296},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"0984621ee1237aa41f0695171dc0528b"},{"name":"AssertionError: unit test failed when testing model with 1","children":[{"name":"test_unit_test_data_type","uid":"fad11974e8112d17","parentUid":"6dd0ec6f9fc64ba3d237ae765337a07f","status":"failed","time":{"start":1753720722612,"stop":1753720723553,"duration":941},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"6dd0ec6f9fc64ba3d237ae765337a07f"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}],"name":"categories"}